language: C

sudo: false

install:
  - travis_wait ./setup/install.sh lsst-sims nose pandas pylint
  - ln -sf /home/travis/miniconda/lib/libssl.so.1.0.0 /home/travis/miniconda/lib/libssl.so.10
  - ln -sf /home/travis/miniconda/lib/libcrypto.so.1.0.0 /home/travis/miniconda/lib/libcrypto.so.10
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - pip install coveralls
  - setup lsst_sims
  - eups declare -r . MyProject -t current
  - setup MyProject

cache:
  directories:
  - $HOME/miniconda.tarball

services:
  - mysql

before_script:
  - mysql -e 'create database myapp_test;'
  - mysql -e 'show databases;'

script:
  - coverage run --source=desc.myproject tests/run_tests.py
  - pylint --py3k `find . -name \*.py -print`

after_success:
  - coveralls
